server:
  port: 8204

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.88.20:3306/shequ-product?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: 123456

  redis:
    host: 192.168.88.20
    port: 6379
    database: 0
    timeout: 1800000
    password: 123456
    lettuce:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

# 启用swagger的增强功能需要使用到的
knife4j:
  enable: true